# Generated by Django 3.2.16 on 2024-03-04 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='profile_picture',
        ),
    ]
