# Generated by Django 3.2.16 on 2024-03-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_hospital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
