# Generated by Django 3.2.16 on 2024-03-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_hospital_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitaldash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
