# Generated by Django 3.2.16 on 2024-03-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20240304_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldash',
            name='fullname',
        ),
    ]
